name: chinese
channels:
  - defaults
dependencies:
  - pip=21.2.4
  - python=3.9.7
  - pip:
      - google-cloud-speech==2.11.0
      - m3u8==0.9.0
      - websockets==10.0
      - azure-cognitiveservices-speech=1.19.0
      - python-dotenv=0.19.2
